FROM golang:1.22-bookworm AS build
WORKDIR /app
COPY . .
RUN BIN="/usr/local/bin" && \
VERSION="1.34.0" && \
curl -sSL \
"https://github.com/bufbuild/buf/releases/download/v${VERSION}/buf-$(uname -s)-$(uname -m)" \
-o "${BIN}/buf" && \
chmod +x "${BIN}/buf"
RUN buf generate
RUN go mod download
RUN go mod verify
RUN go build ./cmd/server


FROM gcr.io/distroless/base-debian12
WORKDIR /app
COPY --from=build /app/server .
CMD [ "./server", "-prod" ]