// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts"
// @generated from file auth.proto (syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { VerifyTokenReq, VerifyTokenRes } from "./auth_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service Auth
 */
export const Auth = {
  typeName: "Auth",
  methods: {
    /**
     * @generated from rpc Auth.VerifyToken
     */
    verifyToken: {
      name: "VerifyToken",
      I: VerifyTokenReq,
      O: VerifyTokenRes,
      kind: MethodKind.Unary,
    },
  },
} as const;
