services:
  auth:
    image: tasjen/messenjo:auth
    container_name: messenjo-auth-prod
    environment:
      - HOST=${HOST}
    build:
      context: ./services/auth
      dockerfile: Dockerfile.prod
    env_file:
      - ./services/auth/.env.prod
    restart: unless-stopped

  chat:
    image: tasjen/messenjo:chat
    container_name: messenjo-chat-prod
    build:
      context: ./services/chat
      dockerfile: Dockerfile.prod
    env_file:
      - ./services/chat/.env.prod
    depends_on:
      - auth
      - redis
    restart: unless-stopped

  streaming:
    image: tasjen/messenjo:streaming
    container_name: messenjo-streaming-prod
    build:
      context: ./services/streaming
      dockerfile: Dockerfile.prod
    env_file:
      - ./services/streaming/.env.prod
    depends_on:
      - auth
      - chat
      - redis
    restart: unless-stopped

  view:
    image: tasjen/messenjo:view
    container_name: messenjo-view-prod
    environment:
      - HOST=${HOST}
    build:
      context: ./services/view
      dockerfile: Dockerfile.prod
    depends_on:
      - chat
      - envoy
    restart: unless-stopped

  redis:
    image: ghcr.io/microsoft/garnet-alpine
    container_name: messenjo-redis-prod
    restart: unless-stopped

  envoy:
    image: envoyproxy/envoy:distroless-v1.30-latest
    container_name: messenjo-envoy-prod
    volumes:
      - ./services/envoy/envoy.yaml:/etc/envoy/envoy.yaml
    attach: false
    depends_on:
      - chat
    restart: unless-stopped

  nginx:
    image: nginx:stable-alpine
    container_name: messenjo-nginx-prod
    volumes:
      - ./services/nginx/nginx.conf.prod:/etc/nginx/nginx.conf:ro
      - ./services/nginx/conf.d:/etc/nginx/conf.d
      - ./services/certbot/conf:/etc/letsencrypt
      - ./services/certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    depends_on:
      - auth
      - view
      - streaming
      - envoy
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: messenjo-pgadmin-prod
    env_file:
      - ./.env.prod
    attach: false

  certbot:
    image: certbot/certbot
    container_name: messenjo-certbot-prod
    profiles:
      - certbot
    volumes:
      - ./services/certbot/conf:/etc/letsencrypt
      - ./services/certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email ${EMAIL} -d ${DOMAIN} --agree-tos
    depends_on:
      - nginx
