FROM node:20-alpine
WORKDIR /app
COPY . .
RUN corepack enable
RUN corepack prepare pnpm@latest --activate
RUN pnpm install
# gcompat is required as uWebSocket.js uses glibc
RUN apk add gcompat
CMD ["pnpm", "run", "dev"]