FROM node:20-alpine
WORKDIR /app
COPY . .
# install packages
RUN corepack enable && \
    corepack prepare pnpm@latest --activate && \
    pnpm install
# gcompat is required as uWebSocket.js uses glibc
RUN apk add gcompat
CMD ["pnpm", "run", "dev"]