// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts"
// @generated from file chat.proto (syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetGroupIdsReq, GetGroupIdsRes } from "./chat_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service Chat
 */
export const Chat = {
  typeName: "Chat",
  methods: {
    /**
     * @generated from rpc Chat.GetGroupIds
     */
    getGroupIds: {
      name: "GetGroupIds",
      I: GetGroupIdsReq,
      O: GetGroupIdsRes,
      kind: MethodKind.Unary,
    },
  }
} as const;

