FROM migrate/migrate as migration


FROM golang:1.22-alpine
WORKDIR /app
ENV IS_PROD false
COPY . .
# to eliminate the error 'failed to initialize build cache at /.cache/go-build'
RUN mkdir /.cache
RUN chmod -R 777 /.cache
RUN go mod download
RUN go mod verify
RUN go install github.com/air-verse/air@latest
COPY --from=migration /usr/local/bin/migrate /usr/local/bin/migrate
CMD ["air"]