FROM golang:1.22-bookworm AS build
WORKDIR /app
COPY . .
RUN go mod download
RUN go mod verify
RUN go build -o ./server ./cmd


FROM gcr.io/distroless/base-debian12
WORKDIR /app
ENV IS_PROD false
COPY --from=build /app/server .
CMD [ "./server" ]