name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      changed-services: ${{ steps.changed.outputs.services }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Determine changed services
        id: changed
        # CHANGED_SERVICES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^services/' | cut -d/ -f2 | sort | uniq)
        run: |
          CHANGED_SERVICES=$(git diff --name-only origin/main HEAD | grep '^services/' | cut -d/ -f2 | sort | uniq)
          CHANGED_SERVICES="[${CHANGED_SERVICES// /,}]"
          echo "Changed services: $CHANGED_SERVICES"
          echo "services=${CHANGED_SERVICES}" >>$GITHUB_OUTPUT

      # - name: Build and push Docker images
      #   if: steps.changed-services.outputs.services
      #   run: |
      #     for SERVICE in ${{ steps.changed-services.outputs.services }}; do
      #       echo "Building and pushing Docker image for service $SERVICE"
      #       docker buildx build --platform linux/amd64,linux/arm64 --push -t x/$SERVICE:latest ./services/$SERVICE
      #     done

  build-and-push:
    needs: check-changes
    # if: ${{ needs.check-changes.outputs.changed-services != '[]' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ${{ needs.check-changes.outputs.changed-services }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: tasjen
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images if changes detected
        if: contains('auth chat streaming view', matrix.service)
        run: |
          echo "Building Docker image for service ${{ matrix.service }}"
          docker buildx build \
          --platform linux/amd64,linux/arm64 \
          -t tasjen/messenjo:${{ matrix.service }} \
          -f services/${{ matrix.service }}/Dockerfile.prod services/${{ matrix.service }} \
          --push
